name: "Release libraries"

on:
  release:
    types: [published]
  # TODO: remove manual dispatch
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        include:
          - {
              runner: macos-latest,
              osname: macOS,
              arch: amd64,
              target: x86_64-apple-darwin,
            }
          - {
              runner: macos-latest,
              osname: macOS,
              arch: arm64,
              target: aarch64-apple-darwin,
            }
          - {
              runner: ubuntu-latest,
              osname: linux,
              arch: amd64,
              target: x86_64-unknown-linux-gnu,
            }
          - {
              runner: ubuntu-latest,
              osname: linux,
              arch: arm64,
              target: aarch64-unknown-linux-gnu,
            }

            # more targets here ...

    name: Release - ${{ matrix.osname }}

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Prepare Release
        run: mv target/${{ matrix.target }}/release/circomkitffi${{ matrix.extension }} ./circomkitffi-${{ matrix.osname }}-${{ matrix.arch }}${{ matrix.extension }}

      - name: Upload Launch Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dkn-compute-binary-${{ matrix.osname }}-${{ matrix.arch }}
          path: dkn-compute-binary-${{ matrix.osname }}-${{ matrix.arch }}${{ matrix.extension }}
